### PR TITLE
Add namespace to build.gradle files for compatibility with Gradle 8

### PR DESCRIPTION
**Pull request by Rexios80**

### CODE REVIEW

**Comment by nathanielheitsch** [comment]
Any update on this?

**Comment by rubenferreira97** [comment]
@hoffmatteo Sorry for the ping. Could you merge this pull request? It's breaking projects with Gradle 8.

**Comment by bardram** [comment]
This all looks good to me.

**Comment by parth-benzatine** [comment]
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file: /Users/parth/.pub-cache/hosted/pub.dev/pedometer-4.0.1/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
         
I am still facing This error in pedometer-4.0.1 please help me

**Comment by parth-benzatine** [comment]
Here is Librery root build.graddle file of Pedometer librery

group 'com.example.pedometer'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.7.10'    
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    defaultConfig {
        minSdkVersion 16
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Pull request merged**
