### PR TITLE
[Health] Match intl package to Flutter SDK

### PR DESCRIPTION
**Pull request by cachapa**
This fixes an incompatibility issue when the SDK and the specified intl package versions differ.
Currently it causes problems when switching between Flutter channels.

A more conservative option is to specify version ranges as suggested in [issue 692](https://github.com/cph-cachet/flutter-plugins/issues/692#issuecomment-1504900313), but that will require more maintenance.

### CODE REVIEW

**Comment by cachapa** [comment]
Health 6.0.0 is once again incompatible with the latest Flutter release because of the `intl` dependency.

**Comment by rafaellop** [comment]
Please accept this PR. The health plugin is again incompatible with stable flutter v3.10.1 which now uses intl 0.18.0

**Comment by jhonatan-3a** [comment]
can we get this ASAP ?

**Comment by hoffmatteo** [comment]
Intl package was updated in today's release.

**Pull request closed without merging**
