### PR TITLE
Added Healthkit Write support

### PR DESCRIPTION
**Pull request by Matthew-Pitzer**
I've added HealthKit write support with the following changes.

### CODE REVIEW

**Comment by thomasnilsson** [comment]
Thanks for the PR, but we would like to have it available on both platforms. Do you know if it is possible on Android as well?

**Comment by Matthew-Pitzer** [comment]
Right now Google has halted any new requests for apps to write to restricted data type for the foreseeable future, which unfortunately happens to encompass pretty much every vital reading. Here's the link where google talks about it: https://developers.google.com/fit/datatypes/restricted.

**Comment by thomasnilsson** [comment]
Thanks a lot. I will take a closer look and merge when I have done so.

**Comment by thomasnilsson** [comment]
@bardram

**Comment by carlleeswanson** [comment]
> Right now Google has halted any new requests for apps to write to restricted data type for the foreseeable future, which unfortunately happens to encompass pretty much every vital reading. Here's the link where google talks about it: https://developers.google.com/fit/datatypes/restricted.

From the link above, it appears to me that Google has not "halted" writing to restricted data types, but rather that the app must be verified for write access to those scopes. If that is true, then it seems that it is the responsibility of the app to ensure that it has the correct scopes and to fail gracefully if not. For those that go through Google's verification process writes "should" work fine. So I hope that you will make this available for both Android and iOS. It would be sad (and confusing) to have parts of this package not work fully on Android.

**Comment by carlleeswanson** [comment]
> Thanks a lot. I will take a closer look and merge when I have done so.

I am concerned/confused about the replacement of Metric units with Imperial units in this PR. That seems like a major breaking change. Wouldn't it be better to _add_ Imperial units if they are needed?

**Comment by Matthew-Pitzer** [comment]
@carlleeswanson I was only conveying that Google will not allow me to request permission to write for my account, so I have no way of testing the code I would have to write to enable Android support as well.

@carlleeswanson The switch of units is a good catch. It should be switched back.

**Comment by carlleeswanson** [comment]
@thomasnilsson Do you have any estimate of when this new (ios-only) write functionality might be released? I'm very eager to use it!

**Comment by bardram** [comment]
Hi @carlleeswanson and @Matthew-Pitzer  -- is this still relevant? Thomas is no longer working for me, but I was looking into this PR and is considering to merge it.

**Comment by carlleeswanson** [comment]
Hi @bardram. Yes, this is still relevant. I think this would be a very useful capability and would like to see it merged. At the same time, I understand and agree with Thomas' desire to have the health package consistent across mobile platforms. Having this functionality available only on iOS makes it less useful.

Do you have an ideas on how we might be able to include the support on Android? Unfortunately, I'm not familiar with Android native development, so can't be of much help. @Matthew-Pitzer, is it possible for you to implement the changes and have @bardram test them in his environment? Any other ideas?

**Comment by bardram** [comment]
Hi all. I will merge this PR. 

BUT - before doing this - is the issue with the Metric versus Imperial metrics solved - @Matthew-Pitzer ?

**Comment by matsunanaro** [comment]
May I ask how's the issue with metric vs imperial unit ? 
I believe many projects would really benefit from the capability of writing to Apple Health and Google Fit!

**Comment by matsunanaro** [comment]
Has anyone started implementing this feature on Android?

If not, I'll start working on it.

**Comment by carlleeswanson** [comment]
Not that I am aware of. IMO, that would be great if you develop it! I would find this functionality very useful.

- Carl

**Comment by bardram** [comment]
Write support on both platforms were added in version 3.3.0

**Pull request closed without merging**
