### PR TITLE
Fixed (regression) issues with metric and permissions

### PR DESCRIPTION
**Pull request by matsunanaro**
This PR fixed regression issue #460 by using metric units for weight, height and body temperatures.

Please refer to issue #460 for more details.

### CODE REVIEW

**Comment by matsunanaro** [comment]
On top of the original issue, a commit was just added to 
- introduce a named optional parameter, "permissions",  into the requestAuthorization method. If unspecified, only READ access will be requested by default.
```
  ///
  /// Requests permissions to access data types in the HealthKit or Google Fit store.
  ///
  /// Returns a Future of true if successful, a Future of false otherwise
  ///
  /// Parameters
  ///
  /// * [types] - a list of [HealthDataType] which the permissions are requested for.
  /// * [permissions] - Optional. 
  ///   + If unspecified, each [HealthDataType] in [types] is requested for READ [HealthDataAccess].
  ///   + If specified, each [HealthDataAccess] in this list is requested for its corresponding indexed 
  ///   entry in [types]. In addition, the length of this list must be equal to that of [types].
  ///
```
- implement the hasPermissions method on both the iOS and Android platforms.

```
  /// Determines if the data types have been granted with the specified access rights.
  ///
  /// Returns: 
  /// 
  /// * true - if all of the data types have been granted with the specfied access rights.
  /// * false - if any of the data types has not been granted with the specified access right(s)
  /// * null - if it can not be determined if the data types have been granted with the specified access right(s).
  ///
  /// Parameters:
  /// 
  /// * [types]  - List of [HealthDataType] whose permissions are to be checked.
  /// * [permissions] - Optional. 
  ///   + If unspecified, this method checks if each HealthDataType in [types] has been granted READ access.
  ///   + If specified, this method checks if each [HealthDataType] in [types] has been granted with the access specified in its 
  ///   corresponding entry in this list. The length of this list must be equal to that of [types].
  /// 
  ///  Caveat:
  /// 
  ///   As Apple HealthKit will not disclose if READ access has been granted for a data type due to privacy concern,
  ///   this method can only return null to represent an undertermined status, if it is called on iOS
  ///   with a READ or READ_WRITE access. 
  /// 
  ///   On Android, this function returns true or false, depending on whether the specified access right has been granted.
  ```
- fix some cosmetic issues on formatting documentation

This PR can therefore fix the following issues:
 - #406
 - #416 
 - #464
 - #466 
 - #467

**Comment by dkbast** [comment]
Is there anything blocking this PR? Im really looking forward to having this fixed and would volunteer for any additional work that needs to be done.

**Comment by paulhulatt** [comment]
Is there any ETA on when this PR will be merged?

**Comment by bardram** [comment]
This PR has been merged and published as version 3.4.0 of the plugin.

Thanks for the PR and sorry about the delay -- not my day job to monitor these plugins.

@dkbast - and others - please check this on Android too. Have only been testing on iOS.

**Pull request merged**
