### PR TITLE
Upgrade to latest Google Fitness SDK and Google Sign-In for Android SDK

### PR DESCRIPTION
**Pull request by traveling-developer**
Suggestion for a new health 3.0.3+1 release to still support flutter in version 1.x and to support the new google guidelines for the fitness sdk.
This could/should also be added to the version 3.0.5 of th health plugin.

Would be great if someone can have a look @thomasnilsson @MadsVSChristensen 
Without this change the health plugin will not work as of the 27. April

### CODE REVIEW

**Comment by matt710** [comment]
Hi @MadsVSChristensen, is there an update on this?

**Review by RickVM — APPROVED** [review]

**Comment by bardram** [comment]
Hi @traveling-developer , @matt710 , @patrickusiewicz , @RickVM :: 

@thomasnilsson (who made this plugin) is no longer working for me, but I'm trying to keep it maintained. As you may have seen, I've merged a couple of PRs lately and the plugin is now in version 3.1.0.

If you think this PR would solve some of the problems mentioned (e.g. in issue #336) then maybe you can create a new PR based on the latest version (in master)?

Since I don't know the technical details of this, I think it would be wise for me **not** to start merging this PR.....

So - would you be able to re-make this PR?

Thanks.

**Comment by traveling-developer** [comment]
Hi @bardram,

I will have a look. But it would be good if we can integrate this change not only in the latest version but also create a version which is not relying on dart 2.12.
Would this be possible for you?

Thanks

**Comment by traveling-developer** [comment]
Already fixed with another pull request

**Pull request closed without merging**
