### PR TITLE
[Health]: Remove Google Fit support

### PR DESCRIPTION
**Pull request by SlimShadyIAm**
Google will soon be turning down support for Google Fit in favor of Google Health Connect in the coming months, and as such we have previously planned to remove support for it in the `health` plugin.

This PR includes also includes a cleanup of the Android code and updates to the documentation.

## Changelog
- Remove Google Fit support in the Android code, as well as Google FIt related dependencies and references throughout the documentation
- Remove `useHealthConnectIfAvailable` from the parameters of `Health().configure()`
- Remove support for various `HealthWorkoutActivityType`s which were supported by Google Fit. Some of these do not have suitable alternatives in Google Health Connect (and are not supported on iOS). The list of removed types include:
  - `MOVE_MINUTES`
  - `AEROBICS`
  - `BIATHALON`
  - `BIKING_HAND`
  - `BIKING_MOUNTAIN`
  - `BIKING_ROAD`
  - `BIKING_SPINNING`
  - `BIKING_UTILITY`
  - `CIRCUIT_TRAINING`
  - `CROSS_FIT`
  - `DIVING`
  - `ELEVATOR`
  - `ESCALATOR`
  - `GARDENING`
  - `HORSEBACK_RIDING`
  - `HOUSEWORK`
  - `IN_VEHICLE`
  - `INTERVAL_TRAINING`
  - `KAYAKING`
  - `KETTLEBELL_TRAINING`
  - `KICK_SCOOTER`
  - `KITE_SURFING`
  - `MEDITATION`
  - `MIXED_MARTIAL_ARTS`
  - `P90X`
  - `POLO`
  - `RUNNING_JOGGING`
  - `RUNNING_SAND`
  - `SKATING_CROSS`
  - `SKATING_INDOOR`
  - `SKATING_INLINE`
  - `SKIING_BACK_COUNTRY`
  - `SKIING_KITE`
  - `SKIING_ROLLER`
  - `SLEDDING`
  - `STANDUP_PADDLEBOARDING`
  - `STILL`
  - `TEAM_SPORTS`
  - `TILTING`
  - `TREADMILL`
  - `VOLLEYBALL_BEACH`
  - `VOLLEYBALL_INDOOR`
  - `WAKEBOARDING`
  - `WALKING_FITNESS`
  - `WALKING_NORDIC`
  - `WALKING_STROLLER`
  - `WALKING_TREADMILL`
  - `WINDSURFING`
  - `ZUMBA`
- Add support for `OTHER` workout type on Android
- Remove the `disconnect` method which was previously used to disconnect from Google Fit.
- Remove the `flowRate` value from `writeBloodOxygen` as this is not supported by Health Connect.

### CODE REVIEW

**Review by yuanchen233 — APPROVED** [review]
LGTM!

**Comment by bardram** [comment]
Remember to add entry to CHANGELOG and bump version before publishing.

**Comment by bardram** [comment]
When testing on iOS and pressing "Add Data" the app throws an uncaught exception:

```
*** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'HKDiscreteQuantitySample 28D6521E-928C-4889-A5A8-C7A4F7B5699D 30 ms  (2024-08-21 16:10:24 +0200 - 2024-08-21 16:30:24 +0200) requires unit of type Mass. Incompatible unit: ms'
```

**Comment by SlimShadyIAm** [comment]
> When testing on iOS and pressing "Add Data" the app throws an uncaught exception:
> 
> ```
> *** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'HKDiscreteQuantitySample 28D6521E-928C-4889-A5A8-C7A4F7B5699D 30 ms  (2024-08-21 16:10:24 +0200 - 2024-08-21 16:30:24 +0200) requires unit of type Mass. Incompatible unit: ms'
> ```

Fixed - when writing health datapoints, we weren't checking if the data type is available on the platform. The example app was trying to write Android-exclusive data.

**Comment by Saurav310799** [comment]
Hi,

I recently updated the health package to version 12.1.0 and encountered the following error:

`error: There's no constant named 'MOVE_MINUTES' in 'HealthDataType'. (undefined_enum_constant at [] lib/fragments/AppOnboardingScreens/AppStepperScreen.dart:1268)`


I checked the changelog but couldn't find any details regarding this change.

What is the alternative for MOVE_MINUTES in the latest version? Any help would be appreciated.

**Pull request merged**
