### PR TITLE
[health] Major upgrades for `intl` and `device_info_plus`

### PR DESCRIPTION
**Pull request by Rexios80**
There seem be no breaking changes that affect this plugin. Please merge as soon as possible since most if not all other packages/plugins have already updated and this plugin is now incompatible with all of them.

This also closes https://github.com/cph-cachet/flutter-plugins/pull/704

### CODE REVIEW

**Comment by Fudal** [comment]
@hoffmatteo Can this PR be merged?

**Comment by hoffmatteo** [comment]
Thank you for the PR, it will be included in the upcoming release!

**Comment by ColtonDevAcc** [comment]
+1

**Comment by Fudal** [comment]
@hoffmatteo when will be next release?

**Comment by kent2508** [comment]
if this merge request is okay, please release new version ASAP, because this package is now incompatible with all of the rest.

**Comment by hoffmatteo** [comment]
The release including this PR was published today!

**Pull request merged**
