### PR TITLE
Added UUID to HealthDataPoint

### PR DESCRIPTION
**Pull request by followthemoney1**
- [x] Added UUID to Health Data Point type
- [x] Added new request with `func getDataWithLimit(call: FlutterMethodCall, result: @escaping FlutterResult) {` to get data by type with limit(It's used for understanding does user already allow permission for dataPoint to read)
- [ ] Refactored and fix merge request (don't have access to resolve conflicts)
- [ ] Update librarye's

### CODE REVIEW

**Comment by followthemoney1** [comment]
Hey, do you need some extra information or we don't want to have these changes at all?

**Comment by followthemoney1** [comment]
@cph-cachet @Whathecode @ltj

**Comment by pjohn** [comment]
@Whathecode @bardram - Is it possible to get these merged? Otherwise it looks like we'll need to fork this change which wouldn't be ideal

**Comment by followthemoney1** [comment]
@pjohn @Whathecode @bardram open new pull request with a simplified solution - https://github.com/cph-cachet/flutter-plugins/pull/706

**Pull request closed without merging**
