### PR TITLE
fix(ios-sleep): Correctly parse sleep data on iOS

### PR DESCRIPTION
**Pull request by fabiocody**

### CODE REVIEW

**Comment by fabiocody** [comment]
Closes #803

**Comment by itsamk** [comment]
SLEEP_LIGHT should also be added here as a data type similar to android. Apple HealthKit refers to it as sleepCore (enum 3). Will greatly appreciate if we can make it part of the next release. 
Reference - https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepcore

**Comment by yedubi** [comment]
> SLEEP_LIGHT should also be added here as a data type similar to android. Apple HealthKit refers to it as sleepCore (enum 3). Will greatly appreciate if we can make it part of the next release. Reference - https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepcore

use SLEEP_ASLEEP for sleepCore
according to health kit [documentation](https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepcore) 
**HKCategoryValueSleepAnalysis**.asleepCore 
`case asleepCore = 3
`
and in [SwiftHealthPlugin.swift](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/health/ios/Classes/SwiftHealthPlugin.swift) of this plugin also used **3**
```
                if dataTypeKey == self.SLEEP_ASLEEP {
                    samplesCategory = samplesCategory.filter { $0.value == 3 }
                }
```

**Comment by fabiocody** [comment]
I'm going to close this as I see the fix has already been included in version 8.1.0

**Pull request closed without merging**
