### PR TITLE
Add insulinDelivery support for iOS

### LINKED ISSUE #674: [health 4.5.0] Add support for insulinDelivery type from HealthKit
[Documentation](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/2867753-insulindelivery).

### PR DESCRIPTION
**Pull request by biklas7**
Closes #674

### CODE REVIEW

**Comment by biklas7** [comment]
In order to write insulin delivery to apple health we need to provide a [reason](https://developer.apple.com/documentation/healthkit/hkinsulindeliveryreason) (basal vs bolus) so I've decided to create a new method channel for it. Please check if that makes sense to you!

**Comment by biklas7** [comment]
@MadsVSChristensen sorry to tag you, but just wanted to ask if it's possible to consider this pull request for future releases? Cheers

**Comment by biklas7** [comment]
@hoffmatteo I've just merged this branch with the latest changes so it should be easier to review, whenever you find time to pick this up 🙂

Only pay attention to my previous comment about parsing the metadata to extract the insulin delivery reason. If I find a solution to that I'll update the pull request again 👍

**Comment by biklas7** [comment]
@bardram Hello 👋 any chance of taking a look into this one? 🙏

**Comment by SlimShadyIAm** [comment]
Hi @biklas7, thanks for your PR and apologies for the long delay. I will review this within the next couple of days.

**Review by SlimShadyIAm — APPROVED** [review]

**Comment by biklas7** [comment]
Thanks for the review @SlimShadyIAm and glad to contribute 👍

**Pull request merged**
